install:
  # LyX
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq
  - sudo apt-get install lyx
  # pandoc
  - sudo apt-get install lyx pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended epubcheck

script:
  - lyx --export pdflatex example.lyx
  - pandoc example.tex -o example.epub
  - epubcheck example.epub
