install:
  # LyX
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq
  - sudo apt-get install lyx
  # pandoc
  - sudo apt-get install lyx pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended epubcheck

script:
  - lyx --export pdflatex example.lyx
  - echo -e "% The Author\n$(cat example.tex)" > example.tex
  - echo -e "% My Title\n$(cat example.tex)" > example.tex
  - pandoc example.tex -o example.epub
  - epubcheck example.epub
  # In one go, bad idea
  #- echo -e "% My Title\n$(cat example.lyx)" > example.lyx
  #- echo -e "% The Author\n$(cat example.lyx)" > example.lyx
  #- pandoc example.lyx -o example.epub
  #- epubcheck example.epub
